### ISSUE TITLE
Preprocess data to remove unused data

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/dependency-size#1]
Since the data provided by PyPI contains a lot of information we don't need, such as the license or author, let's create a function that has:

- input: name of a package
- return: its version, size (in bytes), and its dependency spec.

For example:

- input: `scipy`
- return: `"1.5.4"`, `25879680`, `[<dependency numpy >=1.14.5 >]`

**Comment by dinhanhx** [comment]
```python
{ 'name': 'urllib3',
  'requires_dist': [ ('brotlipy', [('>=', '0.6.0')]),
                     ('pyOpenSSL', [('>=', '0.14')]),
                     ('cryptography', [('>=', '1.3.4')]),
                     ('idna', [('>=', '2.0.0')]),
                     ('certifi', []),
                     ('ipaddress', []),
                     ( 'PySocks',
                       [('>=', '1.5.6'), ('<', '2.0'), ('!=', '1.5.7')])],
  'size': 136770}
```
@Huy-Ngo  what do you think this kind of output?

For the `size` attribute, I take the size of first .whl/build file in `urls` attribute in raw [json data](https://pypi.org/pypi/urllib3/json) because often the first file is for any python for any platform for any architecture.

![image](https://user-images.githubusercontent.com/38489776/102291216-3ce07a80-3f75-11eb-99c8-e238c6a25b6b.png)

**Comment by Huy-Ngo** [comment]
That's alright as long as it's consistent. Please also update the README when you file the PR.
